config/routes.rb
Rails.application.routes.draw do
  resources :comments

  devise_for :users
  get 'pages/about'
get 'about', to: 'pages#about'

  get 'pages/credits'
get 'credits', to: 'pages#credits'

  resources :transcriptions

  root 'transcriptions#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :transcription
  validates :user_name, presence: true, length: { minimum: 2 }
end

app/models/transcription.rb
class Transcription < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
	include Gravtastic
	gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
def create
  @comment = Comment.new(comment_params)
  @transcription = @comment.transcription

  respond_to do |format|
    if @comment.save
      format.html { redirect_to transcription_path(@transcription), notice: 'Comment was successfully created.' }
    else
      format.html { render :new }
      format.json { render json: @comment.errors, status: :unprocessable_entity }
    end
  end
end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :transcription_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
  def credits
  end
end

app/controllers/transcriptions_controller.rb
class TranscriptionsController < ApplicationController
  before_action :set_transcription, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, only: [:edit, :update, :destroy]


  # GET /transcriptions
  # GET /transcriptions.json
  def index
    @transcriptions = Transcription.all
  end

  # GET /transcriptions/1
  # GET /transcriptions/1.json
  def show
  @comments = @transcription.comments.all
  @comment = @transcription.comments.build
end

  # GET /transcriptions/new
  def new
    @transcription = Transcription.new
  end

  # GET /transcriptions/1/edit
  def edit
  end

  # POST /transcriptions
  # POST /transcriptions.json
  def create
    @transcription = Transcription.new(transcription_params)

    respond_to do |format|
      if @transcription.save
        format.html { redirect_to @transcription, notice: 'Transcription was successfully created.' }
        format.json { render :show, status: :created, location: @transcription }
      else
        format.html { render :new }
        format.json { render json: @transcription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transcriptions/1
  # PATCH/PUT /transcriptions/1.json
  def update
    respond_to do |format|
      if @transcription.update(transcription_params)
        format.html { redirect_to @transcription, notice: 'Transcription was successfully updated.' }
        format.json { render :show, status: :ok, location: @transcription }
      else
        format.html { render :edit }
        format.json { render json: @transcription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transcriptions/1
  # DELETE /transcriptions/1.json
  def destroy
    @transcription.destroy
    respond_to do |format|
      format.html { redirect_to transcriptions_url, notice: 'Transcription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transcription
      @transcription = Transcription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transcription_params
      params.require(:transcription).permit(:user_name, :description, :picture, :transcription)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transcriptions_helper.rb
module TranscriptionsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="md-col-12">
    <h2 class="page-header">New Comment</h2>
  </div>
</div>

<div class="row">
  <div class="md-col-4 col-md-offset-1">
    <%= form_for(@comment) do |f| %>
      <% if @comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
          <% @comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.hidden_field :transcription_id %>

      <div class="form-group">
        <%= f.label :user_name %><br>
        <%= f.text_field :user_name, class: "form-control", placeholder: "Your Name" %>
      </div>
      <div class="form-group">
        <%= f.label :body %><br>
        <%= f.text_area :body, class: "form-control", placeholder: "Comment", rows: 5 %>
      </div>

    <div class="actions">
      <%= f.submit "Save", class: "btn btn-default" %>
    </div>
  <% end %>
  </div>
</div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Transcription</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.transcription %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Transcription:</strong>
  <%= @comment.transcription %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scriba</title>
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" %>
<%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css" %>
<%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Roboto" %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<footer>
  <div class="container">
    HILT <%= Time.now.year %>
  </div>
</footer>
<%= javascript_include_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" %>
<body>
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Scriba", root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to "Transcriptions", transcriptions_path %>
        </li>
        <li>
          <p class="navbar-text pull-right">
            <% if user_signed_in? %>
              <%= image_tag current_user.gravatar_url %>
             Logged in as <strong><%= current_user.email %></strong>.
               <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
             <% else %>
                <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
             <% end %>
           </p>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">

  <% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Bacon ipsum dolor sit amet meatball ribeye pork belly capicola shoulder leberkas sirloin. Pig strip steak chicken beef ribs pork chop. Corned beef swine filet mignon tongue pork loin kevin, fatback turkey shankle short loin t-bone kielbasa drumstick pork belly jowl. Tenderloin short ribs strip steak, pork chop shank jerky ground round prosciutto drumstick cow jowl. Ball tip tail swine short loin pancetta. Shankle drumstick turducken jowl strip steak t-bone chicken ham hock bacon landjaeger tri-tip short loin short ribs beef pork.

T-bone jerky corned beef chicken shankle meatloaf frankfurter hamburger short loin pork strip steak leberkas. Ham capicola leberkas ribeye kielbasa. Ham hock filet mignon jerky brisket andouille boudin, salami kielbasa. Tongue capicola pork belly meatball cow meatloaf kielbasa ribeye short loin sausage flank. Meatball strip steak shank ham hock tri-tip meatloaf. Turkey chicken andouille pancetta kielbasa jerky pork loin shank brisket filet mignon. Venison boudin jowl pork chop, pancetta pastrami landjaeger shankle.

Frankfurter ground round fatback, jowl sausage short ribs spare ribs. Drumstick jowl leberkas meatball chicken swine salami chuck. Chicken ground round biltong pancetta strip steak filet mignon chuck pastrami pork brisket tongue andouille meatball ham capicola. Landjaeger swine turducken ground round, ball tip porchetta filet mignon bacon t-bone beef doner pancetta boudin rump. Kielbasa prosciutto swine ground round pork belly shank meatloaf bresaola andouille chicken.</p>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/credits.html.erb
<h1>Credits</h1>
<p>This application was created by me, for this thing I did.</p>
<p>Some other people helped too.</p>

app/views/transcriptions/_edit_form.html.erb
<%= form_for(@transcription, :html => {:multipart => true}, :role => 'form') do |f| %>
  <div class="row">
    <% if @transcription.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@transcription.errors.count, "error") %> prohibited this transcription from being saved:</h2>

        <ul>
        <% @transcription.errors.full_messages.each do |message| %>
          <li class="alert alert-warning"><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control", placeholder: "Document Title", required: true %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control", placeholder: "Document Description" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <% if @transcription.picture.present? %>
          <%= image_tag(@transcription.picture_url, class: "img-responsive") %>
        <% else %>
          <%= f.label :picture %><br>
          <%= f.file_field :picture %>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :transcription %><br>
        <%= f.text_area :transcription, class: "form-control", placeholder: "Transcription", rows: 30 %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="actions">
        <%= f.submit "Save", class: "btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>

app/views/transcriptions/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for(@transcription, :html => {:multipart => true}, :role => 'form') do |f| %>
      <% if @transcription.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@transcription.errors.count, "error") %> prohibited this transcription from being saved:</h2>

          <ul>
          <% @transcription.errors.full_messages.each do |message| %>
            <li class="alert alert-warning"><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, class: "form-control", placeholder: "Document Title" %>
      </div>
      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: "form-control", placeholder: "Document Description" %>
      </div>
      <div class="form-group">
        <%= f.label :picture %><br>
        <%= f.file_field :picture %>
        <p class="help-block">Image for document.</p>
      </div>
      <div class="actions">
        <%= f.submit "Save", class: "btn btn-default" %>
      </div>
    <% end %>
  </div>
</div>

app/views/transcriptions/edit.html.erb
<h1>Editing transcription</h1>

<%= render 'form' %>
<%= render 'edit_form' %>

<%= link_to 'Show', @transcription %> |
<%= link_to 'Back', transcriptions_path %>

app/views/transcriptions/index.html.erb
<div class="row">
  <h1>Transcriptions</h1>

  <p>
    <%= link_to 'New Transcription', new_transcription_path, :class => "btn btn-large btn-primary" %>
  </p>
</div>

<% @transcriptions.in_groups_of(3) do |group| %>
<div class="row">
  <% group.compact.each do |transcription| %>
    <div class="col-xs-6 col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag(transcription.picture_url(:thumb)), transcription_path(transcription)) if transcription.picture.present? %>
        <div class="caption">
          <h3><%= transcription.title %></h3>
          <p><%= truncate(transcription.description, length: 250) %></p>
          <p>
            <%= link_to 'Edit', edit_transcription_path(transcription), :class => "btn btn-mini btn-primary" %>
            <%= link_to 'Destroy', transcription, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger" %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/transcriptions/new.html.erb
<h1>New transcription</h1>

<%= render 'form' %>

<%= link_to 'Back', transcriptions_path %>

app/views/transcriptions/show.html.erb
<% unless notice.nil? %>
<div class="row">
  <div class="col-md-12">
    <p id="notice" class="alert alert-info" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
      </button>
      <%= notice %>
    </p>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-md-12">
    <h1><%= @transcription.title %></h1>
    <h2>Description:</h2>
      <%= @transcription.description %>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <h3>Picture</h3>
    <p>
      <%= image_tag(@transcription.picture_url, class: "img-responsive") if @transcription.picture.present? %>
    </p>
  </div>

  <div class="col-md-6">
    <h3>Transcription</h3>
    <%= simple_format @transcription.transcription %>
  </div>
</div>

<div class="row">
  <%= link_to 'Edit', edit_transcription_path(@transcription), class: "btn btn-primary" %>
  <%= link_to 'Back', transcriptions_path, class: "btn btn-success" %>
</div>

<div class="row">
  <div class="col-md-12">
    <h3 class="page-header">Comments</h3>
  </div>
</div>

<% @comments.each do |comment| %>
<div class="row">
  <div class="md-col-10 col-md-offset-1">
    <div class="comment">
      <p><strong><%= comment.user_name %></strong></p>
      <%= simple_format comment.body %>
    </div>
  </div>
</div>
<% end %>

<%= render 'comments/form' %>